spring:
  application:
    name: employee
  datasource:
    url: jdbc:h2:file:~/employee;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
topics:
  employee-events: "employee.topic"
